### ISSUE TITLE
mismatched types error

### ISSUE THREAD

**Issue by ssshen** [paritytech/wasm-utils#32]
> I'm running:
>
> - **Parity version**: 1.9.0
> - **Operating system**:  MacOS

I extern parity crate, and use ethcore.
when i run cargo build, wasm-utils goes error. Error information as follow:
```
error[E0308]: mismatched types
  --> /Users/ss/.cargo/git/checkouts/wasm-utils-682bf683e263f4f2/78d76bd/src/pack.rs:71:46
   |
71 |                         *entry.field_mut() = CALL_SYMBOL.to_owned();
   |                                              ^^^^^^^^^^^^^^^^^^^^^^ expected str, found struct `std::string::String`
   |
   = note: expected type `str`
              found type `std::string::String`

error[E0277]: the trait bound `str: std::marker::Sized` is not satisfied
  --> /Users/ss/.cargo/git/checkouts/wasm-utils-682bf683e263f4f2/78d76bd/src/pack.rs:71:25
   |
71 |                         *entry.field_mut() = CALL_SYMBOL.to_owned();
   |                         ^^^^^^^^^^^^^^^^^^ `str` does not have a constant size known at compile-time
   |
   = help: the trait `std::marker::Sized` is not implemented for `str`
   = note: the left-hand-side of an assignment must have a statically known size

error: aborting due to 2 previous errors

error: Could not compile `wasm-utils`.
```

Is there something wrong with source code?

**Comment by fckt** [comment]
thanks, @ssshen ! It's fixed by https://github.com/paritytech/wasm-utils/commit/a186c81c03a453dcc4ecf92058457181562550b9#diff-80398c5faae3c069e4e6aa2ed11b28c0

**Comment by ssshen** [comment]
Thanks!
But in parity latest version,  parity->ethcore->wasm->Cargo.toml is still use 
```
parity-wasm = "0.14"
wasm-utils = { git = "https://github.com/paritytech/wasm-utils" }
```
so, the error is still exist.
How can i solve it?
